### PR TITLE
Integrate SBN's Alice & LORRI additions

### PR DESCRIPTION
**Pull request by cgobat**
## Summary
Adds Adeline's Alice stuff and Ben's LORRI stuff. I first merged the [`alice+lorri_classes` branch](https://github.com/pds-data-dictionaries/ldd-nh/tree/alice%2Blorri_classes) into [`resolve_conflicts`](https://github.com/pds-data-dictionaries/ldd-nh/tree/resolve_conflicts), to allow me to perform the required conflict resolution. Now this PR serves to merge `resolve_conflicts` into main.

## Test Data and/or Report
See [CI run #40](https://github.com/pds-data-dictionaries/ldd-nh/actions/runs/9083367347) and [logs](https://github.com/pds-data-dictionaries/ldd-nh/tree/resolve_conflicts/logs).

## Related Issues
- #16
- #19 
- #23
- #24

### CODE REVIEW

**Comment by cgobat** [comment]
@acraugh identified some conflicts/issues to be resolved prior to merging this.

The only "Unresolved" ones that I identified as in-scope/applicable to this pull request were

- "ALICE Spectrograph" and "LORRI imager" were redundant with values already in the `<detector_name>` list of permissible values.
  - I removed the redundant values. I don't care, so it's probably easier to just use these in case they are already implemented in SBN's migration pipeline.
- Conflicting references to the instrument ICD in `<pivot_wavelength>`: `urn:nasa:pds:nh_documents:mission:soc_inst_icd` vs. `urn:nasa:pds:nh_doc:all:soc_inst_icd`
  - The former is the correct LID. Fixed.

So I think this should be mergeable&mdash;let me know if you disagree. We can discuss the other items in the spreadsheet on another ticket.

cc @benjhirsch

**Review by acraugh — APPROVED** [review]
Looks OK, but I'm going to file issues on the missing documentation and regression tests, as well as the aperture value of "airglow", which has a circular definition. The general definition of "airglow" just makes the value more mysterious in the context of an aperture...

**Comment by cgobat** [comment]
Roger that. Thanks for making time for this. I think questions/requests for clarification/docs are probably best referred to Adeline&mdash;none of the Alice content here is mine.

**Comment by acraugh** [comment]
Ah, right. I'll mention it specifically in tomorrow's local meeting, then. I expect it's in the ICD somewhere...

**Pull request merged**
