### PR TITLE
Add `REX_Radiometry_Information` class and associated attributes

### PR DESCRIPTION
**Pull request by cgobat**
## Summary
REX-specific dictionary class and attributes, plus corresponding tests and doc updates.

## Test Data and/or Report
- [test/](https://github.com/pds-data-dictionaries/ldd-nh/tree/feature/rex/test)
- [logs/](https://github.com/pds-data-dictionaries/ldd-nh/tree/feature/rex/logs)

## Related Issues

Partially addresses #21

### CODE REVIEW

**Review by acraugh — CHANGES_REQUESTED** [review]
Looks good but the documentation is missing some updates:

- The new REX class needs to be added to the list under "Top-Level Class" in user-guide.rst (as for MVIC)
- A summary of the REX class needs to be added at the bottom of user-guide.rst (same thing as for MVIC).
- There is no mock-up in the examples/ directory. Since there are several full labels there already, this could be just a segment of label showing what is needed for the REX case only.

**Comment by cgobat** [comment]
Mockup label added (342ddcd) and user's guide updated (2cd3b03). Let me know what you think.

**Review by acraugh — APPROVED** [review]
I noted some minor details that I'm holding over for the next round of general updates and tweaks. The appears to be good to merge.

**Comment by acraugh** [comment]
@cgobat: I know it's been _forever_, but I'm trying to catch up on LDD changes for NH. I've just reviewed the REX changes that have been pending since April in this PR. Nothing major, and in particular nothing I want to hold up merging for. One thing I didn't do was go through the regression test reports in detail, on the assumption that you did at some point when your created them. If that's not true, let me know and I'll check them carefully. If it is close enough to true, let me know and I'll merge.

Oh, and I am going to correct an unclosed italics section in the user_guide.rst file that I noticed.

**Pull request merged**
